# Generated by Django 3.0.7 on 2020-07-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
