# Generated by Django 3.0.7 on 2020-07-11 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_type'),
        ('location', '0002_location_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Chat'),
        ),
    ]
