# Generated by Django 3.0.7 on 2020-07-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_location_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='title',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
