# Generated by Django 3.0.7 on 2020-07-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_location_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='test',
        ),
    ]
