# Generated by Django 3.0.7 on 2020-07-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_remove_location_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
