# Generated by Django 3.0.7 on 2020-07-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'virtual'), (10, 'started'), (20, 'placed'), (100, 'accepted'), (110, 'canceled')], default=10)),
            ],
            options={
                'get_latest_by': ['pk'],
            },
        ),
    ]
