# Generated by Django 3.0.7 on 2020-07-03 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deal', '0001_initial'),
        ('guild', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guild.Guild'),
        ),
    ]
