# Generated by Django 3.0.7 on 2020-06-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singledeal',
            name='deal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='deal.Deal'),
            preserve_default=False,
        ),
    ]
