# Generated by Django 3.0.7 on 2020-07-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
        ),
    ]
