# Generated by Django 3.0.7 on 2020-06-23 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deal', '0002_singledeal_deal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singledeal',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='singledeal',
            name='user',
        ),
        migrations.CreateModel(
            name='SingleDealMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.SingleDeal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='singledeal',
            name='users',
            field=models.ManyToManyField(through='deal.SingleDealMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
