# Generated by Django 3.0.7 on 2020-06-29 15:23

import deal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_auto_20200625_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='accepted',
        ),
        migrations.AddField(
            model_name='deal',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(deal.models.DealStatus['VIRTUAL'], 0), (deal.models.DealStatus['STARTED'], 10), (deal.models.DealStatus['PLACED'], 20), (deal.models.DealStatus['ACCEPTED'], 50), (deal.models.DealStatus['DELETED'], 100)], default=deal.models.DealStatus['VIRTUAL']),
        ),
    ]
