# Generated by Django 3.0.7 on 2020-06-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_auto_20200623_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singledealmember',
            name='single_deal',
        ),
        migrations.RemoveField(
            model_name='singledealmember',
            name='user',
        ),
        migrations.AddField(
            model_name='deal',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SingleDeal',
        ),
        migrations.DeleteModel(
            name='SingleDealMember',
        ),
    ]
