# Generated by Django 3.0.7 on 2020-06-23 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deal', '0004_auto_20200623_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='users',
        ),
        migrations.AddField(
            model_name='deal',
            name='user1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deals_user1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='user2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deals_user2', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
