# Generated by Django 3.0.7 on 2020-06-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0004_auto_20200629_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'virtual'), (10, 'started'), (20, 'placed'), (50, 'accepted'), (100, 'deleted')], default=0),
        ),
    ]
