# Generated by Django 3.0.7 on 2020-07-14 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20200714_2226'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0004_auto_20200714_2226'),
        ('deal', '0004_auto_20200714_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'get_latest_by': ['pk'], 'verbose_name': 'deal', 'verbose_name_plural': 'deals'},
        ),
        migrations.AlterField(
            model_name='deal',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.Market', verbose_name='market'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'virtual'), (10, 'started'), (20, 'placed'), (100, 'accepted'), (110, 'canceled')], default=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_deals', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_deals', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
