# Generated by Django 3.0.7 on 2020-06-23 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deal', '0005_auto_20200623_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='user2',
        ),
        migrations.AddField(
            model_name='deal',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, default=0),
        ),
    ]
