# Generated by Django 3.0.7 on 2020-07-17 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0005_auto_20200714_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VirtualDeal',
        ),
    ]
