# Generated by Django 3.0.7 on 2020-06-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0006_auto_20200629_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualDeal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('deal.deal',),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'virtual'), (10, 'started'), (20, 'placed'), (100, 'accepted'), (110, 'canceled')], default=10),
        ),
    ]
