# Generated by Django 3.0.7 on 2020-06-24 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deal', '0007_auto_20200623_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='dealset',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='deal.DealSet'),
            preserve_default=False,
        ),
    ]
