# Generated by Django 3.0.7 on 2020-06-24 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0008_auto_20200624_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealSetVirtual',
            fields=[
                ('dealset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='deal.DealSet')),
            ],
            options={
                'managed': False,
            },
            bases=('deal.dealset',),
        ),
    ]
