# Generated by Django 3.0.7 on 2020-06-24 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0009_dealsetvirtual'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DealSetVirtual',
        ),
    ]
