# Generated by Django 3.0.7 on 2020-06-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0010_delete_dealsetvirtual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealset',
            name='users',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='dealset',
        ),
    ]
