# Generated by Django 3.0.7 on 2020-06-25 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0001_initial'),
        ('deal', '0011_auto_20200625_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guild.Guild'),
        ),
        migrations.DeleteModel(
            name='DealSet',
        ),
    ]
