# Generated by Django 3.0.7 on 2020-06-25 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deal', '0012_auto_20200625_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='users',
        ),
        migrations.AddField(
            model_name='deal',
            name='partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partner_deals', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_deals', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
