# Generated by Django 3.0.7 on 2020-06-25 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deal', '0014_auto_20200625_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'get_latest_by': ['pk']},
        ),
        migrations.AddField(
            model_name='deal',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deal',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deal',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_deals', to=settings.AUTH_USER_MODEL),
        ),
    ]
