# Generated by Django 3.0.7 on 2020-06-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20200617_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pull',
            name='type',
        ),
        migrations.RemoveField(
            model_name='push',
            name='type',
        ),
    ]
