# Generated by Django 3.0.5 on 2020-04-05 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_listing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.Review'),
        ),
    ]
