# Generated by Django 3.0.7 on 2020-06-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20200620_2242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
