# Generated by Django 3.0.7 on 2020-07-01 17:57

from django.db import migrations, models
import listing.models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20200625_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pull',
            name='image',
            field=models.ImageField(blank=True, upload_to=listing.models.image_path),
        ),
        migrations.AlterField(
            model_name='push',
            name='image',
            field=models.ImageField(blank=True, upload_to=listing.models.image_path),
        ),
    ]
