# Generated by Django 3.0.7 on 2020-07-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20200714_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pull',
            name='test',
        ),
        migrations.RemoveField(
            model_name='push',
            name='test',
        ),
    ]
