# Generated by Django 3.0.7 on 2020-07-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20200704_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='pull',
            name='test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='push',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
