# Generated by Django 3.0.7 on 2020-06-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20200617_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pull',
            old_name='count',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='push',
            old_name='count',
            new_name='quantity',
        ),
    ]
