# Generated by Django 3.0.7 on 2020-07-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20200707_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pull',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'created'), (10, 'paused'), (110, 'deleted')], default=0),
        ),
        migrations.AlterField(
            model_name='push',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'created'), (10, 'paused'), (110, 'deleted')], default=0),
        ),
    ]
