# Generated by Django 3.0.7 on 2020-07-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20200705_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='pull',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'created'), (110, 'deleted')], default=0),
        ),
        migrations.AddField(
            model_name='push',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'created'), (110, 'deleted')], default=0),
        ),
    ]
