# Generated by Django 3.0.7 on 2020-07-14 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import listing.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0005_auto_20200714_2226'),
        ('location', '0004_auto_20200714_2226'),
        ('listing', '0004_auto_20200714_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pull',
            options={'verbose_name': 'pull', 'verbose_name_plural': 'pulls'},
        ),
        migrations.AlterModelOptions(
            name='push',
            options={'verbose_name': 'push', 'verbose_name_plural': 'pushs'},
        ),
        migrations.AlterField(
            model_name='pull',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='pull',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='pull',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='pull',
            name='image',
            field=models.ImageField(blank=True, upload_to=listing.models.image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='pull',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='pull',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='pull',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='pull',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'created'), (10, 'paused'), (110, 'deleted')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='pull',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='pull',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.Unit', verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='pull',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='push',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='push',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='push',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='push',
            name='image',
            field=models.ImageField(blank=True, upload_to=listing.models.image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='push',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='push',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='push',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='push',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'created'), (10, 'paused'), (110, 'deleted')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='push',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='push',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.Unit', verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='push',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='short',
            field=models.CharField(max_length=5, verbose_name='shorttitle'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='title',
            field=models.CharField(max_length=20, verbose_name='title'),
        ),
    ]
