# Generated by Django 3.0.7 on 2020-06-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20200617_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pull',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='push',
            name='reviews',
        ),
    ]
