# Generated by Django 3.0.7 on 2020-07-14 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_auto_20200714_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'unit', 'verbose_name_plural': 'units'},
        ),
    ]
