# Generated by Django 3.0.5 on 2020-04-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_auto_20200405_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
