# Generated by Django 3.0.5 on 2020-04-05 19:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing', '0008_delete_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('count', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('type', models.CharField(choices=[('push', 'Biete'), ('pull', 'Suche')], max_length=4)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.Category')),
                ('reviews', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.Review')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.Unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='push',
            name='category',
        ),
        migrations.RemoveField(
            model_name='push',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='push',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='push',
            name='user',
        ),
        migrations.DeleteModel(
            name='Pull',
        ),
        migrations.DeleteModel(
            name='Push',
        ),
    ]
