# Generated by Django 3.0.7 on 2020-07-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PushFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=30, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Request'), (100, 'Sent'), (110, 'Canceled')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=30, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Request'), (100, 'Sent'), (110, 'Canceled')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
