# Generated by Django 3.0.7 on 2020-07-14 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('listing', '0002_auto_20200714_1425'),
        ('deal', '0004_auto_20200714_1425'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.Deal'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pushfeedback',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pushfeedback',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.Deal'),
        ),
        migrations.AddField(
            model_name='pushfeedback',
            name='push',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.Push'),
        ),
    ]
