# Generated by Django 3.0.7 on 2020-06-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200625_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushfeedback',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Request'), (100, 'Sent'), (110, 'Canceled')], default=0),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Request'), (100, 'Sent'), (110, 'Canceled')], default=0),
        ),
        migrations.AlterField(
            model_name='pushfeedback',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pushfeedback',
            name='subject',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pushfeedback',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='subject',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
