# Generated by Django 3.0.7 on 2020-07-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200704_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushfeedback',
            old_name='push',
            new_name='object',
        ),
        migrations.RenameField(
            model_name='userfeedback',
            old_name='user',
            new_name='object',
        ),
    ]
