# Generated by Django 3.0.7 on 2020-07-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20200705_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushfeedback',
            old_name='object',
            new_name='push',
        ),
        migrations.RenameField(
            model_name='userfeedback',
            old_name='object',
            new_name='user',
        ),
    ]
