# Generated by Django 3.0.7 on 2020-06-30 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0007_auto_20200630_1556'),
        ('feedback', '0003_auto_20200629_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushfeedback',
            name='deal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deal.Deal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='deal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deal.Deal'),
            preserve_default=False,
        ),
    ]
