# Generated by Django 3.0.7 on 2020-07-11 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_type'),
        ('market', '0002_market_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Chat'),
        ),
    ]
