# Generated by Django 3.0.7 on 2020-07-11 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_type'),
        ('market', '0003_auto_20200711_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Chat'),
        ),
    ]
