# Generated by Django 3.0.7 on 2020-07-14 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0004_auto_20200714_2226'),
        ('market', '0003_remove_market_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'verbose_name': 'market', 'verbose_name_plural': 'markets'},
        ),
        migrations.AlterField(
            model_name='market',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='market',
            name='title',
            field=models.CharField(max_length=20, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='market',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
