# Generated by Django 3.0.7 on 2020-07-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20200711_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='_users',
            new_name='users',
        ),
    ]
