# Generated by Django 3.0.7 on 2020-07-14 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20200714_2226'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20200714_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'chat', 'verbose_name_plural': 'chats'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-pk'], 'verbose_name': 'message', 'verbose_name_plural': 'message'},
        ),
        migrations.AlterField(
            model_name='chat',
            name='market',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.Market', verbose_name='market'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'default'), (10, 'user'), (20, 'market'), (100, 'lobby')], default=0, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Chat', verbose_name='chat'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
    ]
