# Generated by Django 3.0.7 on 2020-07-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200707_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'default'), (10, 'user'), (20, 'market'), (30, 'location'), (40, 'deal'), (100, 'lobby')], default=0),
        ),
    ]
