# Generated by Django 3.0.7 on 2020-07-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'default'), (10, 'user'), (20, 'market'), (30, 'location'), (100, 'lobby')], default=0),
        ),
    ]
