# Generated by Django 3.0.8 on 2020-07-15 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20200714_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-type'], 'verbose_name': 'chat', 'verbose_name_plural': 'chats'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='seen_by',
            field=models.ManyToManyField(related_name='seen_messages', to=settings.AUTH_USER_MODEL, verbose_name='seen_by'),
        ),
    ]
