# Generated by Django 3.0.8 on 2020-07-15 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20200715_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='seen_by',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='unseen_by',
            field=models.ManyToManyField(related_name='unseen_messages', to=settings.AUTH_USER_MODEL, verbose_name='unseen_by'),
        ),
    ]
