# Generated by Django 3.0.7 on 2020-07-11 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_remove_location_chat'),
        ('market', '0007_remove_market_chat'),
        ('chat', '0006_auto_20200711_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
        ),
        migrations.AddField(
            model_name='chat',
            name='market',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.Market'),
        ),
    ]
