# Generated by Django 3.0.7 on 2020-06-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deal', '0003_auto_20200625_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualDeal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('deal.deal',),
        ),
    ]
