# Generated by Django 3.0.7 on 2020-07-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'unproved'), (10, 'proved'), (20, 'hidden'), (110, 'deleted')], default=0),
        ),
    ]
