# Generated by Django 3.0.7 on 2020-07-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='hidden',
        ),
    ]
