# Generated by Django 3.0.7 on 2020-07-02 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('guild', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
        ),
    ]
