# Generated by Django 3.0.7 on 2020-07-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200702_1608'),
        ('guild', '0002_guild_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Chat'),
        ),
    ]
