# Generated by Django 3.0.7 on 2020-07-02 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_location_user'),
        ('guild', '0003_auto_20200702_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
        ),
    ]
