# Generated by Django 3.0.7 on 2020-07-19 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='title',
            new_name='name',
        ),
    ]
