# Generated by Django 3.0.5 on 2020-04-04 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200404_0312'),
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Push',
            new_name='Action',
        ),
        migrations.DeleteModel(
            name='Pull',
        ),
    ]
