# Generated by Django 3.0.6 on 2020-07-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_auto_20200719_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='action',
            name='name',
        ),
        migrations.RemoveField(
            model_name='action',
            name='seen_by',
        ),
        migrations.AddField(
            model_name='action',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='time'),
        ),
        migrations.AddField(
            model_name='action',
            name='task',
            field=models.PositiveSmallIntegerField(choices=[(1, 'DAILY_VISIT'), (2, 'USER_CREATED')], default=0, verbose_name='task'),
        ),
    ]
