# Generated by Django 3.0.5 on 2020-04-04 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_action_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='comment',
            new_name='text',
        ),
    ]
