# Generated by Django 3.0.6 on 2020-07-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_auto_20200721_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='exp',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='experience'),
        ),
    ]
