# Generated by Django 3.0.6 on 2020-07-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_action_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='task',
            field=models.PositiveSmallIntegerField(choices=[(1, 'DAILY_VISIT'), (2, 'USER_CREATED'), (3, 'PUSH_CREATED'), (4, 'FIRST_PUSH_CREATED'), (5, 'PULL_CREATED'), (6, 'FIRST_PUll_CREATED'), (7, 'PROFILE_UPDATED'), (8, 'PROFILE_COMPLETE'), (9, 'LOCATION_CREATED'), (10, 'FIRST_LOCATION_CREATED'), (11, 'DEAL_CREATED'), (12, 'BID_CREATED'), (15, 'MARKET_CREATED'), (16, 'FIRST_MARKET_CREATED'), (19, 'FIRST_CHAT_MESSAGE'), (20, 'USER_FEEDBACK_TAKEN'), (21, 'PUSH_FEEDBACK_TAKEN'), (22, 'USER_FEEDBACK_GIVEN'), (23, 'PUSH_FEEDBACK_GIVEN'), (24, 'FIRST_CALC_DIRECT')], default=0, verbose_name='task'),
        ),
    ]
