# Generated by Django 3.0.7 on 2020-07-17 21:35

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deal', '0006_delete_virtualdeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualDeal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('deal.deal',),
        ),
    ]
