# Generated by Django 3.0.5 on 2020-04-04 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pulls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='action.Pull'),
        ),
        migrations.AddField(
            model_name='user',
            name='pushs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='action.Push'),
        ),
    ]
