# Generated by Django 3.0.5 on 2020-04-04 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200404_0231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pushs',
            new_name='action',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pulls',
        ),
    ]
