# Generated by Django 3.0.7 on 2020-07-14 20:26

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='beta_user',
        ),
        migrations.AlterField(
            model_name='user',
            name='config',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserConfig', verbose_name='config'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to=user.models.image_path, verbose_name='image'),
        ),
    ]
