# Generated by Django 3.0.5 on 2020-04-04 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200404_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='action',
        ),
    ]
