# Generated by Django 3.0.7 on 2020-07-03 22:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'unseen'), (10, 'seen'), (30, 'answered'), (100, 'accepted'), (110, 'rejected')], default=0)),
            ],
            options={
                'ordering': ['-datetime'],
                'get_latest_by': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='BidPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bid.Bid')),
            ],
        ),
    ]
