# Generated by Django 3.0.7 on 2020-06-17 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing', '0005_auto_20200617_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'unseen'), (10, 'seen'), (20, 'accepted'), (30, 'answered'), (40, 'rejected')], default=0)),
                ('comment', models.TextField(default='')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BidPush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bid.Bid')),
                ('push', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.Push')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BidPull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bid.Bid')),
                ('pull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.Pull')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='pulls',
            field=models.ManyToManyField(through='bid.BidPull', to='listing.Pull'),
        ),
        migrations.AddField(
            model_name='bid',
            name='pushs',
            field=models.ManyToManyField(through='bid.BidPush', to='listing.Push'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
