# Generated by Django 3.0.6 on 2020-06-02 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pull_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('deal', models.BooleanField(default=False)),
                ('pull_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_pull_deals', to='listing.Listing')),
                ('pull_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_pull_deals', to='listing.Unit')),
                ('push_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_push_deals', to='listing.Listing')),
                ('push_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_push_deals', to='listing.Unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
