# Generated by Django 3.0.6 on 2020-06-09 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='pull_listing',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='pull_quantity',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='pull_unit',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='push_listing',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='push_quantity',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='push_unit',
        ),
        migrations.CreateModel(
            name='BidPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bid.Bid')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.Listing')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='positions',
            field=models.ManyToManyField(through='bid.BidPosition', to='listing.Listing'),
        ),
    ]
