# Generated by Django 3.0.7 on 2020-06-18 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bid', '0002_auto_20200618_1611'),
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='pulls',
            field=models.ManyToManyField(through='bid.BidPull', to='listing.Pull'),
        ),
        migrations.AddField(
            model_name='bid',
            name='pushs',
            field=models.ManyToManyField(through='bid.BidPush', to='listing.Push'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
