# Generated by Django 3.0.7 on 2020-06-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0003_auto_20200620_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-datetime']},
        ),
        migrations.AlterField(
            model_name='bidpull',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bidpush',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
