# Generated by Django 3.0.7 on 2020-06-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0004_auto_20200623_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='comment',
        ),
    ]
