# Generated by Django 3.0.7 on 2020-06-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0004_auto_20200629_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'unseen'), (10, 'seen'), (30, 'answered'), (100, 'accepted'), (110, 'rejected')], default=0),
        ),
    ]
