# Generated by Django 3.0.7 on 2020-06-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0007_auto_20200623_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'get_latest_by': ['-datetime'], 'ordering': ['-datetime']},
        ),
    ]
