# Generated by Django 3.0.7 on 2020-06-24 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0008_auto_20200624_1335'),
        ('bid', '0008_auto_20200624_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidpull',
            name='deal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deal.Deal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bidpush',
            name='deal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deal.Deal'),
            preserve_default=False,
        ),
    ]
