# Generated by Django 3.0.7 on 2020-06-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0009_auto_20200624_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidpull',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='bidpush',
            name='deal',
        ),
    ]
