# Generated by Django 3.0.7 on 2020-06-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0010_auto_20200624_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='pulls',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='pushs',
        ),
    ]
