# Generated by Django 3.0.7 on 2020-06-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0011_auto_20200624_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'get_latest_by': ['datetime'], 'ordering': ['-datetime']},
        ),
    ]
